### ISSUE TITLE
salt-mode depends on salt

### ISSUE THREAD

**Issue by JeffAbrahamson** [glynnforrest/salt-mode#18]
Visiting a new (empty) .sls file invokes salt-mode, which, in the absence of a salt-minion, dies at line 233 or 244, "Error querying Salt minion".  It seems reasonable that a developer should wish to edit an .sls file on a host that is not itself a salt minion.

The constant `salt-mode--query-template` also causes a failure if salt is not configured on the dev machine, since the import of salt.config fails.

Perhaps this is merely a documentation bug: failing to explain what is necessary on a development machine to use salt-mode.el.

**Comment by glynnforrest** [comment]
Thanks for the report @JeffAbrahamson.

This is definitely a bug, the mode should work without a salt-minion. The documentation features should be an added bonus if salt is installed.

I'll see about fixing this shortly.

**Comment by glynnforrest** [comment]
@JeffAbrahamson I've just pushed a commit that should fix this. Once melpa builds the new package, it'd be great if you could update and confirm this solves your problem.
