### ISSUE TITLE
Slows File Open By A Lot

### ISSUE THREAD

**Issue by catvec** [glynnforrest/salt-mode#22]
With no extra configuration installing salt-mode increases the file open time by about 3 seconds.

**Comment by glynnforrest** [comment]
Thanks for reporting @Noah-Huppert. Yes, I believe this slowness is due to the mode calling a salt-minion process for eldoc hints and documentation functions. I'll look into it and try to defer its execution.

**Comment by humitos** [comment]
Thanks for this mode! :)

Is it any workaround available? Like, disabling the eldoc hints?

**Comment by glynnforrest** [comment]
> Is it any workaround available? Like, disabling the eldoc hints?

That might work yes. Sorry for my lack of activity on this issue. I still use this mode almost every day and the slow file open annoys me every time. I normally start emacs when my computer boots and leave it open continuously. I see a slowness the first time I open a `.sls` file, but barely any slowness after that. If you open each `.sls` file by calling `emacs top.sls` you'll see the issue every time, sorry.

I hope to look into this soon!

**Comment by glynnforrest** [comment]
Thanks for waiting @Noah-Huppert and @humitos, this should be fixed by https://github.com/glynnforrest/salt-mode/commit/e76e78d93e4770d42bdde9367a11d0e0836a21c9.
