### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by glynnforrest** [glynnforrest/salt-mode#9]
I'd like to add some testing before the mode gets too big. There is a [travis build](https://travis-ci.org/glynnforrest/salt-mode) that runs the file through `package-lint`, but I'd like to add some tests of functionality as well.

I am aware of ert for unit tests, and ecukes for a cucumber-style approach.

https://www.emacswiki.org/emacs/UnitTesting

@joewreschnig your thoughts on what to use would be appreciated!

**Comment by joewreschnig** [comment]
I'm coming back to the elisp after some years away so I'm pretty ignorant about what's best practice today. I've used ERT and found it acceptable. Ecukes looks a little silly to me; Cucumber (and BDD more generally) developed for languages that don't have a fluent syntax to begin with.

Either way I think this will also require something like Cask, as salt-mode has several non-core dependencies which will need to be installable by CI.

**Comment by glynnforrest** [comment]
Thanks for tip, Cask looks like the way to go.

[Smartparens](https://github.com/Fuco1/smartparens/blob/master/.travis.yml) runs ERT tests on travis using Cask, so I'll use that as a starting point. 

I'll start with ERT, and only consider other frameworks if I'm missing something.

There used to be ecukes tests in the smartparens repo, but they've been removed. Looks like it isn't maintained any more. https://github.com/Fuco1/smartparens/issues/619

**Comment by Fuco1** [comment]
I would recommend https://github.com/jorgenschaefer/emacs-buttercup for new projects.  It's a bit cleaner than ert and scales better I think.  I'm using ert in smartparens for historical reasons (basically rewriting the tests is too much work at this point) but all my other projects use buttercup and it's much more pleasant.

**Comment by glynnforrest** [comment]
Thanks for the tip @Fuco1, I'll look into it!
